// ─── Stock Board Type ─────────────────────────────────────────────────────────
export interface StockBoard {
  sym: string; name: string; exchange: string
  price: number; ref: number; ceil: number; floor: number
  high: number; low: number; open: number; avgPrice: number
  vol: number; totalVal: number
  change: number; changePct: number
  bid: { p: number; v: number }[]
  ask: { p: number; v: number }[]
  foreignBuy: number; foreignSell: number
  updatedAt: number
}

// ─── Index Stock Lists ─────────────────────────────────────────────────────────
export const VN30 = ['ACB','BCM','BID','BVH','CTG','FPT','GAS','GVR','HDB','HPG','MBB','MSN','MWG','NVL','PDR','PLX','POW','SAB','SSI','STB','TCB','TPB','VCB','VHM','VIB','VIC','VJC','VNM','VPB','VRE']

export const VN100 = [
  ...VN30,
  'EIB','LPB','MSB','OCB',
  'VND','HCM','VCI','MBS',
  'KDH','NLG','DXG','HDG','CII','DIG','KBC','SJS','IDC','LHG','CRE',
  'PNJ','KDC','REE','MCH',
  'IMP','DHG',
  'DGC','DRC','HSG','NKG','PHR','DPR',
  'GEX','BWE','VSC','GMD','HAX','SIP','KSB',
  'PVD','PVS','NT2','DCM','DPM','OIL','BSR',
  'QNS','VHC','MPC','ANV','FMC','PAN','STK',
]

export const VN_MIDCAP = [
  'CEO','DCM','DGW','DNP','EVF','GKM','IDJ','KLF','LAS',
  'NBC','NRC','ORS','PLC','PVB','QTC','SHS','TAR','TIG','TNT',
  'TXM','VCS','VGS','VMD','WIN','HUT','SDC','SGT',
  'ANT','ASM','BAF','DHC','DTD','GEX','HBC','HTI','IBC','ITC',
  'KAC','MCG','PTB','QBS','SNG','TSC','TTP','VRG',
  'BST','CHP','CMG','FTS','BFC',
]

export const VN_SMALLCAP = [
  'AAA','ABR','AGG','AGM','ALT','BAB','BBC','BCE','BMI','BMP',
  'BNG','BPC','BRC','BTP','BVB','BVS','CAV','CDC','CDN',
  'CIG','CLX','CSM','CT3','CTF','CTI','CTS',
  'DAG','DAH','DBC','DBD','DBT','DIH','DLG','DMC','DNH',
  'DOP','DPG','DSC','DSE','DSN','DTP','DVP','FCM','FIT',
  'GEG','HCC','HHV','HLD','HNA','HOT','HPX','HTB',
  'ICF','IJC','KBC','KHG',
]

export const VN_DIAMOND    = ['VCB','VIC','VHM','FPT','TCB','ACB','HPG','MWG','VPB','MSN']
export const VN_FIN_LEAD   = ['VCB','BID','CTG','MBB','TCB','VPB','ACB','STB','HDB','EIB','LPB','MSB','VIB','TPB','OCB']
export const VN_FIN_SELECT = ['VCB','BID','CTG','MBB','TCB','VPB','ACB','STB','HDB','EIB','LPB','MSB','VIB','TPB','OCB','SHB','SSI','VND','HCM','VCI','MBS','SHS','VCS','VGS','BVH','PVI']
export const VN_DIVIDEND   = ['VCB','GAS','SAB','VNM','FPT','REE','PNJ','DHG','IMP','NT2','BWE','VCS','GMD','VSC','DPM','DCM','QNS','VHC','PAN','DRC','PHR','KDH','PLC','ANV','GEX','HAX','STK','FMC','DGC','BFC']
export const VN_MITECH     = ['FPT','CMG','ELC','VGI','SGT','FOX','OTS','TST','VTC','GEG','NET','KPT','TNG','SBT','ITD']

export const VN_FIN  = ['VCB','BID','CTG','MBB','TCB','VPB','ACB','STB','HDB','EIB','LPB','MSB','VIB','TPB','OCB','SSI','VND','HCM','VCI','MBS','SHS','SHB','BVH','VRE','PVI']
export const VN_IND  = ['HPG','GEX','BWE','VSC','GMD','HAX','SIP','KSB','VEA','HUT','CTI','PHR','DPR','KBC','IDC','DIG','CII']
export const VN_MAT  = ['HPG','DGC','DRC','HSG','NKG','PHR','DPR','ANV','VHC','KSB','CSV','NHH','HVG']
export const VN_IT   = ['FPT','CMG','ELC','VGI','SGT','FOX','OTS','ITD','TST','NET','KPT','TNG','SBT']
export const VN_REAL = ['VHM','NVL','PDR','VIC','KDH','NLG','DXG','HDG','CII','DIG','KBC','SJS','IDC','LHG','CRE','HDC','AGG','NRC','DXS','QCG']
export const VN_CONS = ['VNM','SAB','MWG','PNJ','KDC','MSN','MCH','BFC','QNS','VHC','MPC','FMC','ANV','DHG','IMP','PLX']
export const VN_ENE  = ['GAS','PLX','POW','PVD','PVS','NT2','OIL','BSR','DCM','DPM','GEG','GVR']
export const VN_HEAL = ['DHG','IMP','OPC','PME','JVC','THP','BMP','DMC','VMD','DBT']

export const HNX30 = ['CEO','DCM','DGW','DNP','DTD','EVF','GKM','IDJ','KLF','LAS','MBS','NBC','NRC','ORS','PLC','PVB','QTC','SHB','SHS','TAR','TIG','TNT','TXM','VCS','VGS','VMD','WIN','HUT','SDC','SGT']

export const HNX_ALL = [
  ...HNX30,
  'AAA','ALT','AMV','ANT','APC','ASM','BAB','BAF','BBC','BCE',
  'BFC','BMI','BMS','BNC','BVB','BVS','CAV','CDC','CDN',
  'CHP','CMG','CMX','CSM','CT3','CTF','CTI','CTS',
  'DAG','DAH','DBC','DBD','DBT','DHC','DIH','DLG',
  'DOP','DPC','DPG','DRH','DSC','DSE','DSN',
  // Extended HNX
  'ACI','ACM','ADC','ADP','ALV','AMD','AME','AMS','API','APT',
  'ARM','ART','AVF','BAM','BBS','BCB','BDB','BHT','BKC','BKG',
  'BLF','BLI','BMC','BNA','BNW','BPC','BPH','BRR','BSA','BSH',
  'BSL','BTD','BTH','BTS','BVG','BXH','C92','CAB','CAN','CCM',
  'CDO','CEO','CID','CJC','CLM','CMS','CMV','CPC','CQN','CSI',
  'CTB','CTN','CTP','CTS','CVN','D11','DAD','DAE','DAP','DC4',
  'DCF','DCH','DCS','DDG','DHN','DHP','DII','DIN','DM7','DNC',
  'DNQ','DNY','DPC','DPP','DPS','DPT','DQC','DSB','DST','DTB',
  'DTC','DTN','DTP','DTQ','DTS','DTT','DTZ','DXB','DZM',
  'EBS','ECI','EIC','ELC','EMC','EVE','FCN','FCS','FDC',
  'GLT','GMC','GNT','GTD','GTN','HAN','HBE','HBS','HCC','HCT',
  'HDA','HDO','HEV','HGM','HHC','HHL','HID','HII','HLD','HLG',
  'HMC','HNA','HNF','HPC','HPM','HPS','HPT','HTC','HTL','HTS',
  'HTV','HUB','HUT','HVT','ICG','IDJ','IVS','KAC','KBC','KCB',
  'KHA','KHB','KHW','KKC','KMR','KPF','KPT','KSF','KTS','L10',
  'L14','L18','L35','L43','L44','L61','L62','LAF','LBC','LBM',
  'LCD','LCS','LDP','LIG','LM3','LM7','LMH','LNC','LUT','MAC',
  'MBG','MCC','MDG','MFG','MHC','MIC','MIM','MKV','MNC','MPT',
  'NAB','NAE','NAG','NAP','NAW','NAX','NCT','NDA','NDN','NED',
  'NGK','NHC','NHP','NHT','NIS','NJC','NLC','NLS','NPS','NRC',
  'NTS','NVB','NVP','OBC','OGC','OHG','ONE','ONW','PAC','PBC',
  'PCG','PCT','PDB','PDT','PEG','PEN','PGS','PGT','PHH','PLC',
  'PMC','PMG','PMW','PMS','PPC','PPP','PPT','PRC','PSD','PSC',
  'PSH','PSI','PSW','PTC','PTL','PVG','PVL','PVT','QHD','QNC',
  'QPH','RAL','RCL','RDP','SAB','SAF','SAP','SAV','SBD','SBS',
  'SCC','SCG','SCJ','SCL','SCS','SCR','SDD','SDN','SDY',
  'SFG','SFI','SGD','SGO','SIC','SII','SKG','SLS','SMB','SMC',
  'SMN','SNC','SNG','SNZ','SPD','SPI','SPM','SPS','SPV','SRA',
  'SRB','SRF','SSB','SSC','SSG','SSM','STC','STH','STP','SVD',
  'SVT','SZL','TAC','TBC','TBD','TBT','TBX','TCJ','TCL','TCM',
  'TCP','TDC','TDG','TDH','TDM','TDN','TDT','TGG','THB','THD',
  'THG','TIE','TIP','TIX','TKC','TLG','TMP','TMT','TN1','TNI',
  'TPC','TPH','TPN','TPR','TQN','TRC','TRT','TTA','TTB','TTF',
  'TTS','TUC','TVA','TVB','TVD','TVH','TVN','TVS','TVT','TWC',
  'UIC','V11','V12','V15','V21','VAB','VBC','VCA','VCC','VCG',
  'VCT','VDB','VDS','VFR','VIG','VIP','VIT','VIX','VKC','VMC',
  'VNA','VNB','VNC','VND','VNE','VNF','VNI','VNL','VNP','VNR',
  'VNS','VNT','VNX','VPC','VPD','VPG','VPH','VPI','VPS','VRC',
  'VRS','VSA','VSB','VSH','VSI','VSM','VST','VTB','VTG','VTO',
  'VTS','VTZ','VXB','XMC','YBM',
]

// ─── Comprehensive HOSE List ───────────────────────────────────────────────────
// All actively traded HOSE stocks
export const HOSE_FULL = Array.from(new Set([
  ...VN100,
  ...VN_MIDCAP,
  ...VN_SMALLCAP,
  // Agriculture / Food
  'AGR','AGM','AGF','AGD','ANH','ANL','APC','BAF','BAS','BLT',
  'CAG','CTP','DAH','FMC','GTN','HAG','HNG','HVG','IDI','LAF',
  'MSN','MPC','NAV','NBB','NSC','PAN','QNS','SBT','TSC','VHC',
  // Banks / Finance
  'ABB','ACB','BAB','BID','BSI','BVH','CTG','EIB','HDB','KLB',
  'LPB','MBB','MSB','NAB','NVB','OCB','PGB','SCB','SGB','SHB',
  'SSB','STB','TCB','TPB','VAB','VBB','VCB','VIB','VPB',
  // Real Estate
  'AGG','ASM','BCG','BCE','BCI','CEO','CII','CRC','CRE','CTA',
  'D2D','DAT','DC2','DIG','DLG','DXG','DXS','EBS','FCN','FLC',
  'HAH','HBC','HDC','HDG','HHV','HID','HLD','HPX','HTB','HTN',
  'IJC','ITC','KBC','KDH','KHG','LCG','LGC','LHG','LM7','MBA',
  'MHC','NBT','NLG','NRC','NTL','NVL','PDR','PTB','QCG','ROS',
  'SCR','SCJ','SDD','SGO','SIC','SII','SJS','SKG','SNG','SVD',
  'TAC','TBC','TDC','TDG','TDH','TDM','TDN','TDT','THD','TIG',
  'TIX','TKC','TNI','UIC','VHM','VIC','VIG','VMC','VNA','VPI',
  'VSH','VSI','XMC',
  // Industry / Materials / Energy
  'AMD','APG','AST','ATA','BMP','BRC','BSR','BTL','BTP','BWE',
  'C47','CAV','CHP','CIG','CLC','CLG','CLW','CNA','COM','CSC',
  'CSM','CTD','CTF','CTI','CTR','CVT','DAG','DBC','DC2','DCD',
  'DGC','DHA','DHM','DHP','DIC','DMC','DNA','DNL','DNW','DOP',
  'DPG','DPM','DPR','DRC','DSN','DTC','DTL','DTP','DVP','EMC',
  'EVE','FCM','FIT','GDT','GEG','GEX','GLT','GMC','GMD','GTA',
  'GTN','GTT','GVR','HAX','HCT','HGM','HII','HMC','HNA','HOT',
  'HPH','HPG','HPT','HSG','HUB','HVN','ICF','ILB','IPH','IVS',
  'JVC','KCS','KHA','KHP','KMR','KPF','KSB','LBM','LIX','LSS',
  'MAC','MCG','MCH','MDG','MKV','MPT','MST','NAF','NFC','NHT',
  'NKG','NLC','NNC','NPM','NTP','NUE','OIL','OPC','PAC','PAP',
  'PAS','PC1','PCC','PCG','PCT','PFV','PGC','PGD','PGI','PGT',
  'PHN','PHR','PIT','PLX','PME','PNJ','POW','PPC','PPP','PRC',
  'PSD','PSH','PSI','PSW','PTC','PTI','PVD','PVG','PVL','PVS','PVT',
  'QBS','RAL','RDP','REE','REI','SAH','SAL','SAM','SAP','SBA',
  'SBD','SCC','SCL','SCS','SFC','SFG','SFI','SGH','SLS','SMB',
  'SMC','SRF','SSC','SSG','STK','SVC','SVT','SZL','TBD','TBX',
  'TCJ','TCL','TCM','TCP','TGG','THG','TIE','TIP','TLG','TMP',
  'TMT','TN1','TPC','TPH','TQN','TRC','TRT','TTA','TTB','TTF',
  'TVB','TVS','TVT','TWC','VBS','VCA','VCC','VCG','VCT','VDB',
  'VDP','VDS','VFC','VFG','VGC','VGP','VHD','VID','VIP','VIT',
  'VIX','VKC','VNE','VNI','VNL','VNM','VNP','VNR','VNS','VNT',
  'VPC','VPD','VPG','VPH','VRE','VST','VTB','VTG','VTO','VTS',
  'VTZ','YBM',
  // Telecom / IT
  'CMG','ELC','FOX','FPT','FTS','ITD','KPT','NET','OTS','SGT',
  'SBT','TNG','TST','VGI','VTC',
]))

export const UPCOM_POPULAR = [
  'ACV','BSR','OIL','MCH','QNS','VGI','FOX','ORG','NTC','MPC',
  'VHC','ANV','VCF','HAX','SIP','KSB','VEA','PAN','FTS','BFC',
  // Extended UPCOM
  'AMV','BMS','BNC','DPC','DRH','DTP','DVP','EVF','GKM',
  'IDJ','KLF','LAS','NBC','ORS','PLC','PVB','QTC','SDC','SHS',
  'TAR','TIG','TNT','TXM','VCS','VGS','VMD','WIN',
  'ACI','ADC','AME','AMS','ARM','ART','AVF','BAM','BBS','BCB',
  'BDB','BHT','BKC','BKG','BLI','BNA','BNW','BPC','BPH',
  'BSA','BSH','BSL','BTD','BTH','BTS','BVG','BXH','C92',
  'CAN','CCM','CDO','CID','CJC','CLM','CMS','CMV','CPC','CQN',
  'CSI','CTB','CTN','CVN','D11','DAD','DAE','DAP','DC4','DCF',
  'DCH','DCS','DDG','DHN','DII','DIN','DM7','DNC','DNQ','DNY',
  'DPP','DPS','DPT','DQC','DSB','DST','DTB','DTN','DTQ','DTS',
  'DTT','DTZ','DXB','DZM','ECI','EIC','EMC','FCS','FDC',
  'GNT','GTD','HAN','HBE','HBS','HDA','HDO','HEV','HHL',
  'HNF','HPC','HPM','HPS','HTC','HTS','HTV','HVT','ICG',
  'KCB','KHB','KHW','KKC','KSF','KTS','L10','L14','L18',
  'L35','L43','L44','L61','L62','LBC','LCD','LCS','LDP',
  'LIG','LM3','LNC','LUT','MBG','MCC','MFG','MIC','MIM',
  'MNC','NAB','NAE','NAG','NAP','NAW','NAX','NCT','NDA',
  'NED','NGK','NHP','NIS','NJC','NLS','NPS','NVP','OBC',
  'OGC','OHG','ONE','ONW','PBC','PDB','PDT','PEG','PEN',
  'PGS','PHH','PMC','PMG','PMW','PMS','PPT','PTL','QPH',
  'RCL','SAF','SAV','SBD','SBS','SCG','SDY','SFG','SGD',
  'SMN','SNC','SNZ','SPD','SPI','SPM','SPS','SPV','SRA',
  'SRB','SSM','STC','STH','STP','TBT','THB','TPN','TPR',
  'TTS','TUC','TVA','TVD','TVH','TVN','V11','V12','V15',
  'V21','VAB','VBC','VFR','VNB','VNC','VNF','VNX','VRC',
  'VRS','VSA','VSB','VSM','VXB',
]

export const EXTENDED = ['EIB','HDB','LPB','MSB','OCB','VIB','TPB','KDC','KDH','NLG','DXG','HDG','REE','VCS','ANV','DGC','DRC','HSG','IMP','PNJ','VND','HCM','MBS','VCI','DPM','DHG','GMD','VSC','NKG','HAG','STK','VHC','BWE','GEX','PVD','PVS','NT2','CII','DIG','SJS','IDC','KBC','LHG','PHR','DPR']

export const COMPANY_NAMES: Record<string, string> = {
  ACB:'NH TMCP Á Châu', BCM:'TCT Becamex IDC', BID:'NH TMCP Đầu tư & PT VN',
  BVH:'TCT Bảo Việt', CTG:'NH TMCP Công Thương VN', FPT:'CTCP Tập đoàn FPT',
  GAS:'TCT Khí VN', GVR:'TCT Cao su VN', HDB:'NH TMCP PT TP.HCM',
  HPG:'CTCP Tập đoàn Hòa Phát', MBB:'NH TMCP Quân Đội', MSN:'CTCP Tập đoàn Masan',
  MWG:'CTCP ĐT Thế Giới Di Động', NVL:'CTCP Tập đoàn Novaland',
  PDR:'CTCP PT BĐS Phát Đạt', PLX:'TCT Xăng dầu VN', POW:'TCT Điện lực Dầu khí VN',
  SAB:'TCT CP Bia-Rượu-NGK Sài Gòn', SSI:'CTCP Chứng khoán SSI',
  STB:'NH TMCP Sài Gòn Thương Tín', TCB:'NH TMCP Kỹ Thương VN',
  TPB:'NH TMCP Tiên Phong', VCB:'NH TMCP Ngoại Thương VN', VHM:'CTCP Vinhomes',
  VIB:'NH TMCP Quốc Tế VN', VIC:'TCT CP Vingroup', VJC:'CTCP Hàng không VietJet',
  VNM:'CTCP Sữa VN', VPB:'NH TMCP Việt Nam Thịnh Vượng', VRE:'CTCP Vincom Retail',
  SHB:'NH TMCP Sài Gòn Hà Nội', EIB:'NH TMCP Xuất Nhập Khẩu VN',
  LPB:'NH TMCP Bưu điện Liên Việt', MSB:'NH TMCP Hàng Hải VN',
  OCB:'NH TMCP Phương Đông', PVB:'NH TMCP Đại Chúng VN',
  MBS:'CTCP CK MB', SHS:'CTCP CK Sài Gòn Hà Nội', VCS:'CTCP Vicostone',
  VGS:'CTCP Ống Thép Việt Đức', DGW:'CTCP Thế Giới Số', PLC:'CTCP Hóa dầu Petrolimex',
  CEO:'CTCP Tập đoàn C.E.O', VND:'CTCP CK VNDirect', HCM:'CTCP CK TP.HCM',
  VCI:'CTCP CK Bản Việt', BVS:'CTCP CK Bảo Việt', BSI:'CTCP CK BIDV',
  KDH:'CTCP ĐT KDH', NLG:'CTCP Nam Long', DXG:'CTCP Tập đoàn Đất Xanh',
  HDG:'CTCP Tập đoàn Hà Đô', CII:'CTCP ĐT Hạ tầng Kỹ thuật TP.HCM',
  DIG:'TCT CP Đầu tư PT Xây dựng', SJS:'CTCP ĐT PT Đô thị & KCN Sông Đà',
  IDC:'TCT IDICO', KBC:'TCT PT Đô thị Kinh Bắc', LHG:'CTCP Long Hậu',
  CRE:'CTCP BĐS Thế Kỷ', HDC:'CTCP PT Nhà Bà Rịa-Vũng Tàu',
  AGG:'CTCP ĐT và PT BĐS An Gia', DXS:'CTCP DXS', QCG:'CTCP Quốc Cường Gia Lai',
  NRC:'CTCP Nam Mê Kông', REE:'CTCP Cơ điện lạnh',
  PNJ:'CTCP Vàng bạc Đá quý Phú Nhuận', KDC:'CTCP Tập đoàn KIDO',
  MCH:'CTCP Hàng tiêu dùng Masan',
  IMP:'CTCP Dược phẩm Imexpharm', DHG:'CTCP Dược Hậu Giang',
  OPC:'CTCP Dược phẩm OPC', PME:'CTCP Pymepharco',
  JVC:'CTCP Thiết bị Y tế Việt Nhật', THP:'CTCP Bia Sài Gòn Miền Tây',
  BMP:'CTCP Nhựa Bình Minh', DMC:'CTCP XNK Y tế Domesco',
  VMD:'CTCP Y Dược - Dụng cụ Y tế VN', DBT:'CTCP Dược phẩm Bến Tre',
  ANV:'CTCP Nam Việt', DGC:'CTCP Tập đoàn Hóa chất ĐG',
  DRC:'CTCP Cao su Đà Nẵng', HSG:'CTCP Tập đoàn Hoa Sen',
  NKG:'CTCP Thép Nam Kim', PHR:'CTCP Cao su Phước Hòa',
  DPR:'CTCP Cao su Đồng Phú', CSV:'CTCP Hóa chất Cơ bản Miền Nam',
  NHH:'CTCP Nhựa Hà Nội', HVG:'CTCP Hùng Vương', KSB:'CTCP Khoáng sản & XD Bình Dương',
  GEX:'CTCP Tập đoàn GELEX', BWE:'CTCP Cấp Thoát nước Bình Dương',
  VSC:'CTCP Container VN', GMD:'CTCP Gemadept', HAX:'CTCP DV Ô tô Hàng Xanh',
  SIP:'CTCP Sài Gòn VRG', VEA:'TCT Máy động lực & Máy NN VN',
  HUT:'CTCP Tasco', SDC:'CTCP Sông Đà Capital', SGT:'CTCP CMC Telecom',
  CTI:'CTCP ĐT PT Cường Thuận IDICO',
  ACV:'TCT Cảng hàng không VN', BSR:'CTCP Lọc hóa dầu Bình Sơn',
  OIL:'CTCP Dầu khí Quốc gia VN', PVD:'CTCP Khoan và DV Khoan dầu khí',
  PVS:'TCT CP DV Kỹ thuật DK', NT2:'CTCP Điện lực Dầu khí Nhơn Trạch 2',
  DCM:'CTCP Phân bón Dầu khí Cà Mau', DPM:'TCT Phân bón & Hóa chất Dầu khí',
  GEG:'CTCP Điện Gia Lai',
  QNS:'CTCP Đường Quảng Ngãi', VHC:'CTCP Vĩnh Hoàn',
  MPC:'CTCP TS Minh Phú', STK:'CTCP Sợi Thế Kỷ',
  PAN:'CTCP PAN', FTS:'CTCP CK FPT', BFC:'CTCP Phân bón Bình Điền',
  FMC:'CTCP Thực phẩm Sao Ta',
  CMG:'CTCP Tập đoàn Công nghệ CMC', ELC:'CTCP Điện tử Elcom',
  VGI:'CTCP Viettel Global', FOX:'CTCP Viễn thông FPT',
  OTS:'CTCP Cảng Đoạn Xá', ITD:'CTCP Công nghệ & TM',
  TST:'CTCP Du lịch & TM TH', VTC:'TCT Truyền thông VN',
  NET:'CTCP Bột giặt Net', KPT:'CTCP Cảng Cam Ranh',
  TNG:'CTCP ĐT & TM TNG', SBT:'CTCP TH Công - Biên Hòa',
  DNP:'CTCP Nhựa DNP', EVF:'CTCP Tài chính APEC',
  GKM:'CTCP Gang thép Cao Bằng', IDJ:'CTCP ĐT IDJ VN',
  KLF:'CTCP ĐT TM & XNK CKL', LAS:'CTCP Supe Phốt phát Lâm Thao',
  NBC:'CTCP Than Núi Béo', ORS:'CTCP CK Tiên Phong',
  TAR:'CTCP NN CNC Trung An', TIG:'CTCP Tập đoàn ĐT VN',
  TNT:'CTCP Tập đoàn TNT', TXM:'CTCP Vimeco', QTC:'CTCP CTGT Quảng Ngãi',
  WIN:'CTCP Định Lượng',
  VCF:'CTCP Vinacafé Biên Hòa', ORG:'CTCP TH True Milk', NTC:'CTCP Nam Tân Cảng',
  HAG:'CTCP Hoàng Anh Gia Lai', MCG:'CTCP Cơ điện & XD VN',
  PTB:'CTCP Phú Tài', ANT:'CTCP Kỹ thuật Khoáng sản', ASM:'CTCP ĐT ASM',
  BAF:'CTCP NN BAF VN', DHC:'CTCP Đông Hải Bến Tre',
  DTD:'CTCP ĐT PT TDT', HBC:'CTCP XD & KD ĐT Hoà Bình',
  HTI:'CTCP ĐT & PT Hạ tầng TH', IBC:'CTCP ĐT APEC',
  ITC:'CTCP ĐT & CN BĐS ITC', KAC:'CTCP ĐT Địa ốc Khang An',
  QBS:'CTCP XNK Quảng Bình', SNG:'CTCP Sông Đà 9',
  TSC:'CTCP VT Kỹ thuật NN Cần Thơ', TTP:'CTCP Bao bì Nhựa TT',
  VRG:'CTCP ĐT VRG', BST:'CTCP Sông Đà 6', CHP:'CTCP TĐ Cửa Đạt',
  PVI:'CTCP Bảo hiểm PVI', PVT:'TCT CP VT Dầu khí',
  DAG:'CTCP Nhựa Đông Á', CSM:'CTCP CN Cao su Miền Nam',
  CMX:'CTCP Camimex Group', DIH:'CTCP ĐT & PT CN Hà Nội',
  DLG:'CTCP Đức Long Gia Lai', DOP:'CTCP Dầu TV Phú Long',
  DPG:'CTCP ĐT PT Nhà & ĐT DPG', DRH:'CTCP DRH Holdings',
  FCM:'CTCP Khai khoáng Miền Trung', HCC:'CTCP Bê tông Hòa Cầm',
  HHV:'CTCP ĐT Hạ tầng GT Đèo Cả',
  // Additional company names
  AGR:'CTCP Giống cây trồng Trung ương',
  FLC:'CTCP Tập đoàn FLC', ROS:'CTCP Xây dựng FLC Faros',
  HAH:'CTCP Vận tải & Xếp dỡ Hải An',
  HVN:'TCT Hàng không VN (Vietnam Airlines)',
  PC1:'CTCP Xây lắp Điện 1', CTD:'CTCP Xây dựng Coteccons',
  REI:'CTCP BĐS Regal', NVB:'NH TMCP Quốc dân',
  VIX:'CTCP CK VIX', SSB:'NH TMCP Đông Nam Á',
  NAB:'NH TMCP Nam Á', KLB:'NH TMCP Kiên Long',
  PGB:'NH TMCP Xăng dầu Petrolimex', SCB:'NH TMCP Sài Gòn',
  SGB:'NH TMCP Sài Gòn Công Thương', VAB:'NH TMCP Việt Á',
  VBB:'NH TMCP Việt Nam Thương Tín', ABB:'NH TMCP An Bình',
  BAB:'NH TMCP Bắc Á',
  CTF:'CTCP City Auto', DVP:'CTCP Đầu tư & PT Cảng Đình Vũ',
  ICF:'CTCP ĐT TM Thủy sản', IJC:'CTCP PT Hạ tầng KCN',
  ILB:'CTCP ĐT & PT An Đô', IPH:'CTCP Đầu tư Năng lượng Hưng Thịnh',
  IVS:'CTCP CK Đầu tư VN', KCS:'CTCP Phát triển KCN Việt Nam',
  KHA:'CTCP Xuất nhập khẩu Khánh Hội',
  KHP:'CTCP Điện lực Khánh Hòa', KMR:'CTCP Mirae',
  KPF:'CTCP ĐT Tài chính KPF', LAF:'CTCP Chế biến Hàng xuất khẩu LT',
  LBM:'CTCP Khoáng sản & VL XD Lâm Đồng',
  LCG:'CTCP LICOGI 16', LGC:'CTCP ĐT Cầu đường CII',
  LIX:'CTCP Bột giặt LIX', LM7:'CTCP Lilama 7',
  LSS:'CTCP Mía đường Lam Sơn', MAC:'CTCP Cung ứng & DV KT Hàng Hải',
  MDG:'CTCP Miền Đông', MHC:'CTCP MHC',
  MKV:'CTCP MKV', MPT:'CTCP ĐT & TM DV Dầu khí',
  MST:'CTCP CK MIBF', NAF:'CTCP Nafoods Group',
  NAV:'CTCP Vận tải Thủy Thanh Niên', NBB:'CTCP ĐT Năm Bảy Bảy',
  NBT:'CTCP Nước sạch Bắc Thái', NDN:'CTCP ĐT PT Nhà Đà Nẵng',
  NFC:'CTCP Phân lân Nung chảy Văn Điển',
  NHT:'CTCP Thủy điện Miền Nam', NLC:'CTCP Ngũ Long Cần Thơ',
  NNC:'CTCP Đá Núi Nhỏ', NPM:'CTCP Việt Nam Kỹ nghệ Bột mì',
  NSC:'CTCP Giống cây trồng Miền Nam', NTL:'CTCP PT Đô thị Từ Liêm',
  NTP:'CTCP Nhựa Thiếu niên Tiền Phong', NUE:'CTCP Thực phẩm NUE',
  PAC:'CTCP Pin Ắc quy Miền Nam', PAP:'CTCP Khoáng sản Phú Yên',
  PAS:'CTCP Dịch vụ Phân tích In', PCG:'CTCP Kinh doanh Khí hóa lỏng MN',
  PCT:'CTCP Cảng Quốc tế Hải Phòng', PFV:'CTCP Hóa chất PFV',
  PGC:'CTCP Gas Petechim', PGD:'CTCP Phân phối Khí thấp áp PV',
  PGI:'TCT CP Bảo hiểm Petrolimex', PGT:'CTCP GT Holdings',
  PHN:'CTCP Pin Hà Nội', PIT:'CTCP Xuất nhập khẩu Petrolimex',
  PPC:'CTCP Nhiệt điện Phả Lại', PPP:'CTCP Tài chính PT PT',
  PRC:'CTCP Logistics Portserco', PSD:'CTCP DV Phân phối Tổng hợp Dầu khí',
  PSH:'CTCP Thương mại Đầu tư PSH', PSI:'CTCP CK Dầu khí',
  PSW:'CTCP Cấp nước Phú Hòa Tân', PTC:'CTCP PT Hạ tầng VN',
  PTI:'CTCP Bảo hiểm Bưu điện', PVG:'CTCP Kinh doanh LPG VN',
  PVL:'CTCP ĐT PT BĐS Dầu khí VN',
  RAL:'CTCP Bóng đèn Phích nước Rạng Đông',
  RDP:'CTCP Nhựa Rạng Đông',
  SAH:'CTCP Ô tô Sài Gòn', SAL:'CTCP DV Hàng hải SAL',
  SAM:'CTCP SAM Holdings', SAP:'CTCP SAP',
  SBA:'CTCP Sông Ba', SBD:'CTCP Bia Sài Gòn - Bình Dương',
  SCC:'CTCP XD & KD SCC', SCL:'CTCP Sông Đà Cảnh quan Đô thị',
  SCS:'CTCP DV Hàng hóa Sài Gòn', SCR:'CTCP Địa ốc Sài Gòn Thương Tín',
  SDD:'CTCP ĐT & XD Điện Mêkông', SDN:'CTCP Sơn Đồng Nai',
  SDP:'CTCP Sơn Đà Phước Hòa', SFC:'CTCP Nhiên liệu Sài Gòn',
  SFG:'CTCP Phân bón Miền Nam', SFI:'CTCP ĐT & PT DV Hàng hải',
  SGH:'CTCP KS Sài Gòn', SKG:'CTCP Tàu cao tốc Superdong Kiên Giang',
  SLS:'CTCP Mía đường Sơn La', SMB:'CTCP Bia Sài Gòn - Miền Trung',
  SMC:'CTCP ĐT TM SMC', SRF:'CTCP Kỹ nghệ Lạnh',
  SSC:'CTCP Giống cây trồng Miền Nam', SSG:'CTCP Vận chuyển Sài Gòn Tourist',
  SVC:'CTCP DV Tổng hợp Sài Gòn', SVD:'CTCP PT SVC',
  SVT:'CTCP Công nghệ SVT', SZL:'CTCP Sonadezi Long Thành',
  TAC:'CTCP Dầu thực vật Tường An', TBC:'CTCP Thủy điện Thác Bà',
  TBD:'CTCP Thủy điện Thác Bà', TBX:'CTCP Xi măng Thái Bình',
  TCJ:'CTCP Công nghiệp Gốm sứ Taicera', TCL:'CTCP Đại lý Vận tải SAFI',
  TCM:'CTCP Dệt may - ĐT - TM Thành Công', TCP:'CTCP Xây dựng VN (TCP)',
  TDC:'CTCP Kinh doanh & PT Bình Dương', TDG:'CTCP Đầu tư TDG Global',
  TDH:'CTCP PT Nhà Thủ Đức', TDM:'CTCP Nước Thủ Dầu Một',
  TDN:'CTCP Thép Tây Đô Nha Trang', TDT:'CTCP Tường Đài',
  TGG:'CTCP The Green Group', THD:'CTCP Thaiholdings',
  THG:'CTCP ĐT & XD Tiền Giang', TIE:'CTCP ĐT & PT Điện Tây Bắc',
  TIP:'CTCP Phát triển Khu Công nghiệp Tín Nghĩa',
  TLG:'CTCP Tập đoàn Thiên Long', TMP:'CTCP Thủy điện Thác Mơ',
  TMT:'CTCP Ô tô TMT', TN1:'CTCP Thành Nhơn',
  TNI:'CTCP Tòa nhà Thành Nhơn', TPC:'CTCP Nhựa Tân Đại Hưng',
  TPH:'CTCP Thủy sản Thái Bình', TQN:'CTCP Xi măng Quán Triều VVMI',
  TRC:'CTCP Cao su Tây Ninh', TRT:'CTCP Tôn Đông Á',
  TTA:'CTCP Thủy điện TTA', TTB:'CTCP Tập đoàn Trường Tiền',
  TTF:'CTCP Tập đoàn Kỹ nghệ Gỗ Trường Thành',
  TVB:'CTCP Chứng khoán Trí Việt', TVS:'CTCP CK Thiên Việt',
  TVT:'TCT CP VT Dầu khí Thái Bình Dương', TWC:'CTCP Cấp nước Trà Vinh',
  UIC:'CTCP ĐT PT Nhà & ĐT KCN',
  VBS:'CTCP CK VNDirect (Saigon)', VCA:'CTCP Hàng không VietJet (VCA)',
  VCC:'CTCP Xi măng Vicem Hải Vân', VCG:'TCT XD Số 1 CTCP',
  VCT:'CTCP Vinatex International', VDB:'CTCP PT VDB',
  VDP:'CTCP Dược phẩm Trung ương Vidipha', VDS:'CTCP Radii VN',
  VFC:'CTCP Vinafco', VFG:'CTCP Khử trùng VN',
  VGC:'TCT Viglacera', VGP:'CTCP Cảng Rau Quả',
  VHD:'CTCP PT Nhà và ĐT VHD', VID:'CTCP ĐT PT Thương mại VID',
  VIG:'CTCP ĐT & PT ĐT VIG', VIP:'CTCP Vận tải Xăng dầu VIPCO',
  VIT:'CTCP Gạch ngói Vitaly', VKC:'CTCP Cáp nhựa Vĩnh Khánh',
  VMC:'CTCP Vật liệu XD Việt Mỹ', VNA:'CTCP Vận tải Biển Vinaship',
  VNE:'TCT PT Đường cao tốc VN', VNI:'CTCP ĐT VNI',
  VNL:'CTCP Logistics Vinalink', VNP:'CTCP VNP Group',
  VNR:'TCT CP Tái BH VN', VNS:'CTCP Ánh Dương VN',
  VNT:'CTCP Giao nhận Kho vận Ngoại thương', VPC:'CTCP VP Capital',
  VPD:'CTCP PT điện lực Vinacomin',
  VPG:'CTCP ĐT Thương mại XNK Việt Phát',
  VPH:'CTCP Vạn Phát Hưng', VPI:'CTCP ĐT VPI',
  VSH:'CTCP Thủy điện Vĩnh Sơn Sông Hinh',
  VSI:'CTCP ĐT & XD Cấp thoát nước', VST:'CTCP VOSCO',
  VTB:'NH Công thương VN - CN TP.HCM', VTG:'CTCP VTGAS',
  VTO:'CTCP Vận tải Xăng dầu VN Vitaco',
  VTS:'CTCP Viettronics Tân Bình', VTZ:'CTCP Sản xuất xuất nhập khẩu VTZ',
  XMC:'CTCP ĐT và XD XMC', YBM:'CTCP Khoáng sản YBM',
}
